### PR TITLE
Reintroducing ecrecover and implementing ed25519 signature verification

### PR DESCRIPTION
**Pull request by smblucker**
These changes reintroduce functionality for ecrecover implement ed25519 signature verification as defined here:

https://github.com/ethereum/go-ethereum/pull/16453

### CODE REVIEW

**Comment by silasdavis** [comment]
Happy to have these in. We'll not want to import the secp library that you have there, when this is merged (this week hopefully): https://github.com/hyperledger/burrow/pull/776 we'll be using the btcsuite library for that.

I'll hold off reviewing those changes until you're able to integrate with our keys stuff - some things will also have moved around.

Makes sense to provide these as snatives, and when we have secp support back in we should also re-enable ECRECOVER In vm.go

**Comment by b00f** [comment]
This change is very useful. Thanks for introducing new method: `EdVerify`.
Hopefully this PR will merge soon. 
Thanks @smblucker

**Comment by silasdavis** [comment]
@smblucker or @b00f if you have time/desire to work on this then let me know it's not mergeable at present due both to conflicts and the secp C dependency.

**Comment by vetal20600** [comment]
@smblucker hello. I am trying to apply your commit to my instance burrow based on 0.24.4. then I an going to utilize it in chaincode for hyperledger fabric.

**Pull request closed without merging**
