### PR TITLE
Fix the Table of Contents in README.md

### PR DESCRIPTION
**Pull request by qpakzk**
PR again! Previous PR was #720 .

### CODE REVIEW

**Comment by zramsay** [comment]
this is fixed on `develop` branch from #700

**Comment by qpakzk** [comment]
The master branch has Table of Contents. But develop branch doesn't have Table of Contents.

**Comment by zramsay** [comment]
@qpakzk yes I know, the whole README was fixed in #700. `develop` is the working branch for this repo, and the ToC was removed because it was unecessary.

**Comment by qpakzk** [comment]
@zramsay Now I understand! Thank you!

**Pull request closed without merging**
