### PR TITLE
Add test 49 returndatacopy

### PR DESCRIPTION
**Pull request by fulldecent**
https://github.com/hyperledger/burrow/pull/767#issuecomment-413200966

### CODE REVIEW

**Comment by silasdavis** [comment]
This looks good @fulldecent ... looks like there is a failure in a governance test, may be teething problems with our move of burrow deploy. Could you rebase against develop to see if that fixes it - otherwise I'll just merge and look into it.

**Comment by fulldecent** [comment]
Found test bug, rerunning

**Comment by fulldecent** [comment]
@silasdavis OK, I got my tests to pass, I think the remainder now is not related to me

**Comment by silasdavis** [comment]
Thanks for this, please let me know via issues or on Hyperledger chat if you've be interested in working on any other issues. We are always looking for additional maintainers.

**Pull request merged**
