### PR TITLE
[EVM] Support EXTCODEHASH

### LINKED ISSUE #996: Support EXTCODEHASH
See: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1052.md

### PR DESCRIPTION
**Pull request by phymbert**
Fixes #996

Signed-off-by: phymbert <pierrick.hymbert@gmail.com>

### CODE REVIEW

**Comment by gregdhill** [comment]
LGTM

**Comment by phymbert** [comment]
Thanks @gregdhill , wait before merging, I am trying to add an integration test. Also @silasdavis should we check as in `EXTCODECOPY` if the address references a native contract ?

**Comment by phymbert** [comment]
Well, it is not possible to add intergation test at the moment, `extcodehash` is marked as `C`

> Constantinople is still in planning and all instructions marked as such will result in an invalid instruction exception

OK to merge this first implementation as is

**Comment by seanyoung** [comment]
This might expose a problem in our implementation of the evm. When we deploy code via CallTx, the constructor arguments are concatenated to the bytecode. So, in effect, a contract with a string constructor foo("a") will have a different hash than foo("b").

**Pull request merged**
